### PR TITLE
Some more suggested changes. :-)

### PR DESCRIPTION
**Pull request by Maikuolan**
- Some JavaScript files, which contained no PHP code, were using the PHP extension. Better to only process files in PHP when they contain PHP code.
- Adds Composer support, in order to allow TCPDF to be included directly into the project and to be easily updated whenever necessary.
- Updates existing integration and hooks.
- Commit updates references to the minimum required PHP version.
- Commit also updates cleans up the index pages, and adds links to the various resources referenced by the index pages.

### CODE REVIEW

**Review by KarlosFanta — COMMENTED** [review]
Howzit. hi Maikuolan. THank you for contributing!
Unfortunately i have zero experience with accepting review changes
Unfortunately i have zero experience with merging pull stuff.
This github terminology is so confusing. And maybe I don;t understand your suggestions.
Is all the pink stuff that you deleted?

i see you are deleting TCPDF authors?
invJQuery.php - must this file be removed? it looks like your revicew suggestion deleted it.
Oh I see, that you prefer the .js extension, but there are 6 other files incluing this php file so I don;t want to change the exension.

**Comment by Maikuolan** [comment]
> Howzit. hi Maikuolan. THank you for contributing!
> Unfortunately i have zero experience with accepting review changes
> Unfortunately i have zero experience with merging pull stuff.

You're welcome, and no problem. :-)

> This github terminology is so confusing. And maybe I don;t understand your suggestions.
> Is all the pink stuff that you deleted?

When viewing a set of changes (or a "diff") at GitHub, the pinkish/reddish lines prefixed with a minus ("-") are deletions/removals, and the greenish lines prefixed with a plus ("+") are additions. Taking in mind, of course, that since a "diff" only shows lines added or deleted, that when an existing line is *modified*, it isn't shown as a single change, but as two changes (an addition and a deletion/removal; the removal will show the existing line prior to the modification, and the addition will show the existing line after the modification).

As an example, if we take this text:

```
Hello world
Testing one two three
What's up
```

And then change the "one two three" into a "four five six", we'll see something roughly like this:

```Diff
 1  1  Hello world
-2     Testing one two three
+   2  Testing four five six
 3  3  What's up
+   4  Other random additions...
```

> i see you are deleting TCPDF authors?

Only at the specific files where you can see it, but yeah, I can see the problem with that. Actually, there were some experimental changes I was playing around with (which aren't included in this pull request), committed to a different branch, and the removal of the comments in the headers of the affected files are a bit of cross-bleed from those experimental changes, I think. I didn't notice it when first sending this pull request (but, since it's been spotted, it can be avoided, so no worries; that's one of the good things about reviewing changes before pulling them). :-)

As a clarification to that experimentation: I was thinking about the possibility of more thoroughly refactoring everything, which would include splitting away the necessary parts from those files to something else entirely, something cleaner, not so heavily integrated with dependencies (TCPDF), splitting HTML from the PHP files and into their own files (like a templating system), and thus removing those header comments (since the entire files would've been eventually removed too anyway), but the changes started looking like they'd be way, way too big, too ambitious, and far too difficult to eventually review, so I ended up stopping halfway through and canning the idea. But, in short: Something which doesn't belong in this pull request (so, if we merge this pull request, either, I'll fix that beforehand, or we don't worry about merging this and just close it). '^.^

> invJQuery.php - must this file be removed? it looks like your revicew suggestion deleted it.
> Oh I see, that you prefer the .js extension, but there are 6 other files incluing this php file so I don;t want to change the exension.

Yep, you understood correctly. :-)

And no worries. I would not say that it *must* be removed; to say that I *prefer* the JS extension (that is, for files which contain only JavaScript, which aren't mixed with other languages, like PHP, HTML, etc) would be correct. Generally, the same preference would apply for any files which contain code or markup belonging to only a single language (that I would prefer extensions that naturally correspond to those languages, e.g., HTML for HTML, PHP for PHP and so on).

There's a theoretical security aspect to that preference, too: If a file is intended to only contain a single language, but accidentally or inadvertently contains potentially malicious code from some other language, preventing it from being interpreted or executed in the context of those other languages (e.g., preventing a JavaScript-only file being processed by PHP) could prevent that potentially malicious code from execution, thus nullifying some potential attack vectors.

But, I wouldn't be concerned about that in this particular case, since the files in question aren't mutable (i.e., don't self-modify, and can't be directly edited by outside third-parties), and don't already contain anything malicious or potentially executable in such a way. I just mention the security aspect to provide some basis for my preferences. ;-)

The 6 other files in question: I actually spotted those already, and already modified them accordingly within this pull request, so those require calls to the renamed files shouldn't break as a result of this pull request. But, even so, if you don't want to change the extension, I understand, and no worries (after all, since the change is a preference, and isn't directly fixing any known bugs or problems).

Anyway, I can remove commits from the pull request if needed, so that's not a problem to undo before merging (but, can't be easily fixed after merging, so definitely something to fix beforehand).

The smallest change included in this pull request (increasing the minimum PHP requirement mentioned from PHP 5.3 to PHP 5.4), is probably the most valuable change here, I think (since the basis for it is a call, which seems likely important, in one of your PHP files to a PHP function which wasn't introduced to PHP until 5.4).

The more significant change here is the introduction of Composer. To me, it feels like a good idea, but something which I should ask, which I didn't ask before: Are you familiar with Composer? Or, do you use Composer at your end? If not, integrating it would probably be a bad idea, since it would be difficult to maintain something at a package which the maintainer isn't familiar with or doesn't tend to use.

My thinking is that integrating it in this way, would allow to automatically update TCPDF, saving time which would've otherwise been spent updating it manually. But, if it's something unfamiliar or not well-used, I should remove that from the pull request too.

**Comment by KarlosFanta** [comment]
Unfortunately I do not have experience with Composer. Unfortuantely the latest version of this PDF Invoice project i use is hardcoded and modified for myself so I cannot always look back at this code. But I am dreaming of combining my customized code with InvoicePlane one day. How does one accpet/authorize(/merge?) only some of your code corrections?

**Comment by Maikuolan** [comment]
> How does one accpet/authorize(/merge?) only some of your code corrections?

The best way to do that, I think, would be to "rebase" the commits. Unfortunately, the GitHub UI doesn't currently provide an easy way to do that, but it can be done from command line (e.g., Git bash) reasonably easily. Should I do that from my end? I can do that, if you'd like. :-)

**Comment by Maikuolan** [comment]
(Git also provides the ability to "cherry pick" commits when merging pull requests, but the GitHub UI also doesn't seem to support that yet unfortunately, so the cherry pick method would need to be done through command line as well at the moment).

**Pull request closed without merging**
